trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    ng build --prod
  displayName: 'npm build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Ultimate with MSDN(58ac0bb4-4071-48f2-9b4e-c078a4e061eb)'
    appType: 'webAppLinux'
    WebAppName: 'mctsummit'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist/MCTSummit'